### ISSUE TITLE
Libvirt provider: failed to build

### ISSUE THREAD

**Issue by mkumatag** [openshift/installer#1931]
# Version

latest master branch

# Platform:

# What happened?

While building the code with following build command, failed to build the binary:

```shell
# TAGS=libvirt hack/build.sh
```

error1:
```
+ go build -ldflags ' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-1211-g63c63a0015f8f7cd894a93c0a6c0d6565ee8d05a-dirty -X github.com/openshift/installer/pkg/version.Commit=63c63a0015f8f7cd894a93c0a6c0d6565ee8d05a -s -w' -tags 'libvirt release' -o bin/openshift-install ./cmd/openshift-install
pkg/destroy/libvirt/register.go:6:2: cannot find package "github.com/openshift/installer/pkg/providers" in any of:
	/root/openshift_ws/src/github.com/openshift/installer/vendor/github.com/openshift/installer/pkg/providers (vendor tree)
	/usr/local/go/src/github.com/openshift/installer/pkg/providers (from $GOROOT)
	/root/openshift_ws/src/github.com/openshift/installer/pkg/providers (from $GOPATH)
```

error2:
```
+ go build -ldflags ' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-1211-g63c63a0015f8f7cd894a93c0a6c0d6565ee8d05a-dirty -X github.com/openshift/installer/pkg/version.Commit=63c63a0015f8f7cd894a93c0a6c0d6565ee8d05a -s -w' -tags 'libvirt release' -o bin/openshift-install ./cmd/openshift-install
# github.com/openshift/installer/pkg/destroy/libvirt
pkg/destroy/libvirt/libvirt.go:50:47: undefined: types
```
# What you expected to happen?

Build should work properly and generate installer binary

# How to reproduce it (as minimally and precisely as possible)?

```console
$ TAGS=libvirt hack/build.sh
```

# Anything else we need to know?

I see it as a regression issue introduced in code refactoring happened in https://github.com/openshift/installer/pull/1926

# References

- enter text here.
